//
//  XCUIElement+Name.swift
//  UIRobotTesting
//
//  Created by Andreas Günther on 18.09.25.
//

import XCTest

extension XCUIElement.ElementType {

    var name: String {
        switch self {
            case .any:
                return ""
            case .button:
                return "Button"
            case .staticText:
                return "StaticText"
            case .textField:
                return "TextField"
            case .cell:
                return "Cell"
            case .window:
                return "Window"
            case .application:
                return "app"
            case .group:
                return "Group"
            case .sheet:
                return "Sheet"
            case .drawer:
                return "Drawer"
            case .alert:
                return "Alert"
            case .dialog:
                return "Dialog"
            case .radioButton:
                return "RadioButton"
            case .radioGroup:
                return "RadioGroup"
            case .checkBox:
                return "CheckBox"
            case .disclosureTriangle:
                return "DisclosureTriangle"
            case .popUpButton:
                return "PopUpButton"
            case .comboBox:
                return "ComboBox"
            case .menuButton:
                return "MenuButton"
            case .toolbarButton:
                return "ToolbarButton"
            case .popover:
                return "Popover"
            case .keyboard:
                return "Keyboard"
            case .key:
                return "Key"
            case .navigationBar:
                return "NavigationBar"
            case .tabBar:
                return "TabBar"
            case .tabGroup:
                return "TabGroup"
            case .toolbar:
                return "Toolbar"
            case .statusBar:
                return "StatusBar"
            case .table:
                return "Table"
            case .tableRow:
                return "TableRow"
            case .tableColumn:
                return "TableColumn"
            case .outline:
                return "Outline"
            case .outlineRow:
                return "OutlineRow"
            case .browser:
                return "Browser"
            case .collectionView:
                return "CollectionView"
            case .slider:
                return "Slider"
            case .pageIndicator:
                return "PageIndicator"
            case .progressIndicator:
                return "ProgressIndicator"
            case .activityIndicator:
                return "ActivityIndicator"
            case .segmentedControl:
                return "SegmentedControl"
            case .picker:
                return "Picker"
            case .pickerWheel:
                return "PickerWheel"
            case .switch:
                return "Switch"
            case .toggle:
                return "Toggle"
            case .link:
                return "Link"
            case .image:
                return "Image"
            case .icon:
                return "Icon"
            case .searchField:
                return "SearchField"
            case .scrollView:
                return "ScrollView"
            case .scrollBar:
                return "ScrollBar"
            case .secureTextField:
                return "SecureTextField"
            case .datePicker:
                return "DatePicker"
            case .textView:
                return "TextView"
            case .menu:
                return "Menu"
            case .menuItem:
                return "MenuItem"
            case .menuBar:
                return "MenuBar"
            case .menuBarItem:
                return "MenuBarItem"
            case .map:
                return "Map"
            case .webView:
                return "WebView"
            case .incrementArrow:
                return "IncrementArrow"
            case .decrementArrow:
                return "DecrementArrow"
            case .timeline:
                return "Timeline"
            case .ratingIndicator:
                return "RatingIndicator"
            case .valueIndicator:
                return "ValueIndicator"
            case .splitGroup:
                return "SplitGroup"
            case .splitter:
                return "Splitter"
            case .relevanceIndicator:
                return "RelevanceIndicator"
            case .colorWell:
                return "ColorWell"
            case .helpTag:
                return "HelpTag"
            case .matte:
                return "Matte"
            case .dockItem:
                return "DockItem"
            case .ruler:
                return "Ruler"
            case .rulerMarker:
                return "RulerMarker"
            case .grid:
                return "Grid"
            case .levelIndicator:
                return "LevelIndicator"
            case .layoutArea:
                return "LayoutArea"
            case .layoutItem:
                return "LayoutItem"
            case .handle:
                return "Handle"
            case .stepper:
                return "Stepper"
            case .tab:
                return "Tab"
            case .touchBar:
                return "TouchBar"
            case .statusItem:
                return "StatusItem"
            case .other:
                return "Other"
            @unknown default:
                return "Unknown(\(rawValue))"
        }
    }
}
